name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit-algorithme:
    runs-on: ubuntu-latest
    env:
      working-directory: ./algorithme
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install "poetry>=1.8.5,<2"
        poetry install --with dev
    - name: Run pre-commit
      working-directory: ${{env.working-directory}}
      run: |
        source .venv/bin/activate
        pre-commit run --show-diff-on-failure --color=always --all-files
